### ISSUE TITLE
draw Marker

### ISSUE THREAD

**Issue by zenggpzqbx** [geoman-io/leaflet-geoman#1359] opened 2023-06-02 14:21 UTC
Hello, when I draw a Marker, Markerw cannot display the default icon.

**Comment by Falke-Design** [comment] 2023-06-03 13:13
Can you please share more information.
1. Code
2. Image / video
3. live demo

**Comment by Falke-Design** [comment] 2023-06-24 09:21
Duplicate of #1364

**Closed by Falke-Design** 2023-06-24 09:21 UTC
Labels: needs more info
