### ISSUE TITLE
L.PM.setOptIn(true) causes Text Layer input to be disabled.

### ISSUE THREAD

**Issue by dvazquez-lightbox** [geoman-io/leaflet-geoman#1227] opened 2022-09-14 00:11 UTC
Hey everyone, I'm not sure if this is a bug but when setOptIn is set to true and the user clicks the text layer button the input shows up with pm-disabled tag. Is there a way to have the text layer input enabled and setOptin set to true at the same time?

Steps to reproduce: add L.PM.setOptIn(true); , click the text layer button and place the input on the map. the result is the input is disabled. 
<img width="617" alt="Screen Shot 2022-09-13 at 5 10 55 PM" src="https://user-images.githubusercontent.com/105678133/190031000-2ebbc8ea-4bc2-46a4-81c8-6e435f98831a.png">

**Comment by Falke-Design** [comment] 2022-10-16 19:00
Duplicate of #1186

**Closed by Falke-Design** 2022-10-16 19:00 UTC
