### ISSUE TITLE
Rectangle editing mode is wrong in 1.8

### ISSUE THREAD

**Issue by mcck** [geoman-io/leaflet-geoman#1228] opened 2022-09-15 08:58 UTC
leaflet version：1.8

@geoman-io/leaflet-geoman-free：2.13.0

Add Rectangle, edit it, and it will become a straight line。

https://user-images.githubusercontent.com/20223048/190363122-27d580d8-2fea-4a96-8f7d-a515865d30b9.mp4

**Comment by Falke-Design** [comment] 2022-10-16 17:32
I can't reproduce this issue.

![rectangle-edit-not-working](https://user-images.githubusercontent.com/19800037/196049566-805c6252-cfd9-4559-a4d2-d5579ae4e194.gif)

Can you please more informations? Maybe a problem of your code?

I will close this until we have more infomartion.

**Closed by Falke-Design** 2022-10-16 17:32 UTC
