### ISSUE TITLE
A error in 2.16.0

### ISSUE THREAD

**Issue by huang-jue** [geoman-io/leaflet-geoman#1468] opened 2024-03-21 06:56 UTC
When I added @geoman-io/leaflet-geoman-free@2.16.0, he reported an error：
![beb9d1126ff75ef31c50204445771b50](https://github.com/geoman-io/leaflet-geoman/assets/64304278/c8cf4527-c997-48c7-b20c-f3d1adda3a6e)

**Comment by huang-jue** [comment] 2024-03-21 07:04
When i use import "@geoman-io/leaflet-geoman-free/dist/leaflet-geoman.min.js",this way, the error above will not be reported.But he told me add Controls is undefined.
![110066c98fb297439d44fdf7dba9d90f](https://github.com/geoman-io/leaflet-geoman/assets/64304278/466a15e9-c646-4b77-b6a6-26cf9487c873)

**Comment by Falke-Design** [comment] 2024-03-22 17:08
Release notes:

> This is only relevant for projects using very old versions of babel/webpack loaders
> 
> This version introduces new build tools in the library build toolchain. More specifically we have swapped webpack for eslint. This has improved our build speeds and made the build pipeline simpler and easier to maintain going forward.
However the move to esbuild has also caused the library build assets (minified js files) to be compiled using a more modern version of ECMAScript. The current build files now use the [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) ?. syntax and this can cause issues with projects using older versions of webpack/babel or similar loaders.
> 
> If you face issues with upgrading to version v2.16.0 we suggest that you upgrade your own loaders and build toolchain to a version compatible with modern ECMAScript syntax.

Duplicate of #1458

**Closed by Falke-Design** 2024-03-22 17:08 UTC

**Comment by huang-jue** [comment] 2024-03-25 06:22
This is an old project, and if I upgrade, it means I have to redevelop many things
