### ISSUE TITLE
Error while edit layer

### ISSUE THREAD

**Issue by CityBelfast** [geoman-io/leaflet-geoman#761] opened 2021-01-18 16:50 UTC
Hi, I'm getting error when I do the following steps with geoman drawing tool.

1.  load existing geometry into $LayerDrawItems group Layer
2.  edit the loaded geometry by edit layer button

![image](https://user-images.githubusercontent.com/76213912/104940485-b7078300-59a9-11eb-92e0-edf1205d2185.png)

![image](https://user-images.githubusercontent.com/76213912/104940468-ae16b180-59a9-11eb-908f-0fe025180972.png)

![image](https://user-images.githubusercontent.com/76213912/104940521-c38bdb80-59a9-11eb-9527-8fbe613c4b6a.png)

![image](https://user-images.githubusercontent.com/76213912/104954696-a282b500-59c0-11eb-9acd-a7fd59637ac7.png)

```
let $LayerDrawItems = new L.FeatureGroup();
Map.addLayer($LayerDrawItems);

_**Load existing geometry and attach to drawing tool at initial page load**_
 L.Proj.geoJson(data, {
                    onEachFeature: function (feature, layer) {           
                         layer.groupName = "editBoundary";   
                         layer.options.snapIgnore = true;        
                         $LayerDrawItems.addLayer(layer);
                     }
                });

_**Create Layer Event**_
function Create (e) {
            debugger;
            let layer = e.layer, type = e.shape;
            layer.groupName = layer.options.groupName;  			
			}

_**Configurations**_
 var drawOptions = {
                        snappable: true, snapDistance: 20, snapMiddle: true, allowSelfIntersection: false,                     
                        cursorMarker: true,
                        finishondoubleclick: true,
                        layerGroup: $LayerDrawItems
                    };
                    Map.pm.setGlobalOptions(drawOptions)                                                     
                    Map.pm.Draw.Polygon.setPathOptions({ opacity: 0.7, weight: 2, snapIgnore: true,  groupName:"editBoundary"});
                    Map.pm.Draw.Rectangle.setPathOptions({ opacity: 0.7, weight: 2, snapIgnore: true,   groupName: "editBoundary" });
                    Map.pm.Draw.Line.setPathOptions({ opacity: 0.7, weight: 2, snapIgnore: true,   groupName: "editBoundary" });
                    Map.pm.Draw.Circle.setPathOptions({ opacity: 0.7, weight: 2, snapIgnore: true,  groupName: "editBoundary" });                                                            
                    Map.pm.disableDraw();
                    Map.pm.addControls({ editMode: true, oneBlock: true, cutPolygon: false, drawCircleMarker: false });   
```

https://user-images.githubusercontent.com/76213912/104944720-86c2e300-59af-11eb-84e6-58b2617cc596.MOV

**Comment by Falke-Design** [comment] 2021-01-18 19:34
I was not able to reproduce this. Is it possible that you upload this to a server, so that I can look on it?

Else here my attempt: https://jsfiddle.net/falkedesign/cuasby2j/


Also try to use the newest version of Leaflet 1.7.1

**Comment by CityBelfast** [comment] 2021-01-18 23:15
I couldn't replicate the issue on this link ->  https://jsfiddle.net/falkedesign/cuasby2j/.

Also, I'm not able to replicate the issue on my POC project. Whereas, the error I'm getting it in our Dev environment. As you suggested, I will try to update leaflet library with the latest version. I'm just wondering is it something do with order of leaflet files as I'm using leaflet.draw-1.0.4.js just above geoman file to support existing functionality.

                      "~/Scripts/static/leaflet-1.4.0.js",
                       "~/Scripts/static/leaflet.markercluster-src-1.4.1.js",
                        "~/Scripts/static/spin.min.js",
                        "~/Scripts/static/leaflet.spin.min.js",
                         "~/Scripts/static/leaflet.pattern.js",
                         "~/Scripts/static/proj4-2.5.0.js",
                         "~/Scripts/static/proj4leaflet-1.0.2.min.js",
                         "**~/Scripts/static/leaflet.draw-1.0.4.js",**
                         ""~/Scripts/static/leaflet.geoman.min_js",
                         "~/Scripts/static/leaflet.geoman-pmlock_js,

**Comment by Falke-Design** [comment] 2021-01-19 07:50
I don't think that this makes a problem. This is really strange...

Out of interest what are these functions they are you using from leaflet-draw?

**Comment by CityBelfast** [comment] 2021-01-19 09:55
We use leaflet-draw tool for our existing functionality to plot normal boundary. But this tool doesn't support multi-geometry editing. That is the reason, we are trying to use leaflet-geoman

**Comment by Falke-Design** [comment] 2021-01-19 10:11
So you are not missing any functions of leaflet-draw in geoman? 👍

**Comment by CityBelfast** [comment] 2021-01-19 10:42
I don't think so as there are a few extra functionality exists in geoman like multi-geometry, snapping, drag geometry, which makes this tool more attractive to use it.  hopefully the bug will get resolved once I update with the latest leaflet version. I will let you know the outcome of version upgrade.

**Comment by CityBelfast** [comment] 2021-01-19 21:37
the leaflet libary got updated with 1.7.1 version. but I'm still getting the error when move small circle marker while editing geometry. In fact,  this issue is only in Dev system. 

![image](https://user-images.githubusercontent.com/76213912/105095899-39716f00-5a9e-11eb-8174-e9fb2500dbc8.png)

**Comment by Falke-Design** [comment] 2021-01-19 21:48
It would be very helpful to have the code. Would it possible that you send me the project over Google Drive or so?

Can you debug it in the browser? If you don't know how, I can make you an description

**Comment by CityBelfast** [comment] 2021-01-19 22:15
it is a massive project. As per company policy, it's not allowed me to copy anything outside. would you please make a description to debug it in the browser please?

**Comment by Falke-Design** [comment] 2021-01-20 16:13
I think that you use the npm modul of geoman, if not it is the similar behaviour but in a different source folder:

https://user-images.githubusercontent.com/19800037/105202174-fb2d8b80-5b41-11eb-8130-4b86256b8a22.mp4

I'm interested what are the value of the variable which calls `forEach` where the error is thrown. Because normally the variable is always an array, so I don't understand why it is not anymore an array.

Also please click on the script-link "leaflet.geoman.min.js:1" at `i.handleLayerAdditionInGlobalEditMode (leaflet.geoman.min.js:1)` in the error. And expand the script same as in the video and then please send me an screenshot if it looks different as in the video.

**Comment by CityBelfast** [comment] 2021-01-20 16:47
here is the screenshot. but addedLayers array is undefined.
 ![image](https://user-images.githubusercontent.com/76213912/105207171-1cd94380-5b3f-11eb-826f-6230a1c68102.png)

**Comment by CityBelfast** [comment] 2021-01-20 17:17
I'm just wondering, is it something do with the blow line of code as I'm adding layers directly to group layer rather than adding into map.

  **this.map.on("layeradd", this._layerAdded, this),**

**Comment by Falke-Design** [comment] 2021-01-20 17:24
Can you please try to use 
```
var data = JSON.parse("{\"type\":\"Feature\",\"properties\":{},\"geometry\":{\"type\":\"Polygon\",\"coordinates\":[[[-236.601563,57.891497],[-193.007813,14.264383],[-260.507813,-17.644022],[-186.679688,6.664608],[-223.242188,-55.37911],[-133.945313,17.978733],[-136.757813,62.431074],[-236.601563,57.891497]]]}}");
    L.geoJSON(data,{
```

instead of `L.Proj.geoJson(features, {`

**Comment by Falke-Design** [comment] 2021-01-20 17:35
> this.map.on("layeradd", this._layerAdded, this),

This should not be a problem, also it is working for me

>do you think pointToLayer needs to be changed as I'm using L.circle and L.marker?

this should also make no problems.



Can you please set a break point / debug point here:
```
            this.throttledReInitEdit || (this.throttledReInitEdit = L.Util.throttle(this.handleLayerAdditionInGlobalEditMode, 100, this)),
            this._addedLayers = [],
            this.map.on("layeradd", this._layerAdded, this),
```

is the new debug point called when you enable edit mode?

After enableing the edit mode check in the console if the map has the array:
```
map.pm._addedLayers
```

**Comment by CityBelfast** [comment] 2021-01-20 17:41
> Can you please try to use
> 
> ```
> var data = JSON.parse("{\"type\":\"Feature\",\"properties\":{},\"geometry\":{\"type\":\"Polygon\",\"coordinates\":[[[-236.601563,57.891497],[-193.007813,14.264383],[-260.507813,-17.644022],[-186.679688,6.664608],[-223.242188,-55.37911],[-133.945313,17.978733],[-136.757813,62.431074],[-236.601563,57.891497]]]}}");
>     L.geoJSON(data,{
> ```
> 
> instead of `L.Proj.geoJson(features, {`

sorry this coordinates are outside of our map. we use OS UK map.

**Comment by Falke-Design** [comment] 2021-01-20 17:42
What are the center of your map? `map.getCenter()`

**Comment by CityBelfast** [comment] 2021-01-20 17:43
> What are the center of your map? `map.getCenter()`

 E:278657 | N:187307

**Comment by Falke-Design** [comment] 2021-01-20 17:51
It's not possible for me to convert this into latlng, which crs system are you using? 
It should be possible to get the center in latlng or not?
Have your tried the debug steps?

I'm now AFK but I think im lastest in 40mins back

**Comment by CityBelfast** [comment] 2021-01-20 17:53
> It's not possible for me to convert this into latlng, which crs system are you using?
> It should be possible to get the center in latlng or not?
> Have your tried the debug steps?
> 
> I'm now AFK but I think im lastest in 40mins back

here is the lat/lng for those values
51.571534 , -3.7522848

**Comment by CityBelfast** [comment] 2021-01-20 17:58
> > this.map.on("layeradd", this._layerAdded, this),
> 
> This should not be a problem, also it is working for me
> 
> > do you think pointToLayer needs to be changed as I'm using L.circle and L.marker?
> 
> this should also make no problems.
> 
> Can you please set a break point / debug point here:
> 
> ```
>             this.throttledReInitEdit || (this.throttledReInitEdit = L.Util.throttle(this.handleLayerAdditionInGlobalEditMode, 100, this)),
>             this._addedLayers = [],
>             this.map.on("layeradd", this._layerAdded, this),
> ```
> 
> is the new debug point called when you enable edit mode?
> 
> After enableing the edit mode check in the console if the map has the array:
> 
> ```
> map.pm._addedLayers
> ```
yes I've set a break point but the pointer doesn't come over there

**Comment by CityBelfast** [comment] 2021-01-20 18:03
I don't know whether it is a problem for the library but i just want to highlight one more point here that  all my code is within self invoking function like below

(function (gisenq) {
         code is here....
})(gisenq);

**Comment by CityBelfast** [comment] 2021-01-20 18:10
would you like to have a hangout call?

**Comment by CityBelfast** [comment] 2021-01-20 18:12
Hi , would you like to have a hangout call to see the issue?

**Comment by Falke-Design** [comment] 2021-01-20 18:20
Yes send me please the invite link to design.falke@gmail.com

**Comment by Falke-Design** [comment] 2021-01-20 21:03
The error was because of the PMLock library.

@CityBelfast it'is fixed now: https://raw.githubusercontent.com/Falke-Design/PMLock/master/js/pmLock.js

**Closed by Falke-Design** 2021-01-20 21:03 UTC

**Comment by CityBelfast** [comment] 2021-01-20 21:58
> The error was because of the PMLock library.
> 
> @CityBelfast it'is fixed now: https://raw.githubusercontent.com/Falke-Design/PMLock/master/js/pmLock.js

Thank you so much
