### ISSUE TITLE
Typescript incomplete definition 'pm:new|edit" event

### ISSUE THREAD

**Issue by hoetmaaiers** [geoman-io/leaflet-geoman#1163] opened 2022-05-11 09:08 UTC
Could it be that I found some incomplete Typescript definition?
The `pm:create` and `pm:edit` events have a layer property. This layer should have a `toGeoJSON` function available?

```
 map.on("pm:create", (event) => {
  setMarker(event.layer.toGeoJSON());
});
```

**Comment by Falke-Design** [comment] 2022-05-11 09:27
Duplicate of #945

You need to cast the layer:
```
map.on("pm:create", (e) => {
  if(e.shape === 'Polygon'){
     (e.layer as Polygon).toGeoJSON();
  }
}
```

**Closed by Falke-Design** 2022-05-11 09:27 UTC
