### ISSUE TITLE
DragMode does not work correctly on mobile devices

### ISSUE THREAD

**Issue by Norrikor** [geoman-io/leaflet-geoman#1421] opened 2023-11-22 13:00 UTC
I have a task to build a mobile application based on the web version.

Everything works fine in the browser, everything works on the mobile device except dragMode.

After updating the leaflet-geoman library, I also began to receive the warning: wrong listener type: undefined

And here is the error when dragMode is active, when I try to move a point/polygon/line (if a click, then _onClick, if an attempt to drag, then _onMouseMove): Uncaught TypeError: K(...)._onClick is not a function
     at NewClass._canvasTouchClick (leaflet-geoman.min.js:1:1)
     at HTMLCanvasElement.handler (leaflet-src.js:2799:1)

You are my last hope, I no longer know where to look and what to think, thank you in advance for your time!

**Comment by Falke-Design** [comment] 2024-03-26 18:52
I'm not able to reproduce this. I will close this until new information are available.

**Closed by Falke-Design** 2024-03-26 18:52 UTC
