### ISSUE TITLE
Invalid poly with touching holes

### ISSUE THREAD

**Issue by ashmigelski** [geoman-io/leaflet-geoman#396] opened 2019-01-25 11:13 UTC
After update faced bug.
I use `allowSelfIntersection: false` for polygon. After cut 2 touching holes it became invalid (red).

![peek 2019-01-25 14-02](https://user-images.githubusercontent.com/4904519/51742565-285a1700-20ab-11e9-93f2-d34fbd1a821a.gif)

I think it's valid poly, there's no self intersection. In previous versions worked as needed

**Comment by codeofsumit** [comment] 2019-01-25 15:24
Ou ou ou ok, thanks a lot for reporting this 👍
There are multiple problems at play here.

1. When cutting a polygon, the self-intersection of the resulting layer is not checked during draw.
2. The resulting layers self-intersection is handled when it's added to the map, but doesn't resolve (as in: removes the red style) when the self-intersection is taken care of
3. Cutting two triangles with a shared vertex results in a shape where they are merged and in fact, represent an intersected polygon (like an infinity symbol ♾️).

Thinking about solutions:
1. I'm not sure if I should fix that right now. It would mean I have to simlulate the cutting at every event and calculate possible intersections each time against all layers that are cut. It seems like a huge complexity with little benefit.
2. This needs fixing, I'm on that right now.
3. The current version of Turfs `difference` implementation (which I'm using for the cut feature) has some problems that will be fixed in their next version - but I do not know if this is one of those problems or expected behaviour. TL;DR: I will not tackle this until I can upgrade to turf v7 that will fix existing problems for cutting.

**Comment by ashmigelski** [comment] 2019-01-25 15:42
> 1. When cutting a polygon, the self-intersection of the resulting layer is not checked during draw.

> 1. I'm not sure if I should fix that right now. It would mean I have to simlulate the cutting at every event and calculate possible intersections each time against all layers that are cut. It seems like a huge complexity with little benefit.

You're right, its not huge problem. I implemented it on my app side with our restrictions: after cut you can get multi-polygon but it's not allowed in business logic, so I revert it manually

But poly must be blue, not red ;)

**Comment by codeofsumit** [comment] 2019-01-25 15:58
The polygon will now correctly revert to blue when the self-intersection is solved:
![triangle-cut](https://user-images.githubusercontent.com/2399810/51756793-2059a180-20c2-11e9-9575-8a246ad3309e.gif)

But there are still two problems:
1. The layer still is red when added to the map 🤔, Again, I'm not sure if a shared vertex counts as self intersection or not
2. Sometimes the resulting layer really is a self intersection like you can see here:
![triangle-cut2](https://user-images.githubusercontent.com/2399810/51756870-497a3200-20c2-11e9-8ffe-7d5e0924e267.gif)
In that case, the red color is appropriate. I don't understand when the result is merged to an infinity ♾️ symbol (= self-intersection).

Both issues are bad but I don't want to tackle them until the Turf update is out.

**Comment by timelyportfolio** [comment] 2019-01-27 18:46
@tim-salabim good question.  `allowSelfIntersection` is buried fairly deeply in the `pmDrawOptions()` and `pmEditOptions()`.  Should we make `allowSelfIntersection = FALSE` the default in `mapedit` even though `true` is the default in `Leaflet.pm`?  


```
library(mapview)
library(leafpm)

library(leaflet)
library(mapview)
library(leafpm)

mapview(trails[1,])@map %>%
  addPmToolbar(
    targetGroup = "trails[1, ]",
    drawOptions = pmDrawOptions(allowSelfIntersection = FALSE),
    editOptions = pmEditOptions(allowSelfIntersection = FALSE)
  )
library(leaflet)
library(mapview)
library(leafpm)

mapview(trails[1,])@map %>%
  addPmToolbar(
    targetGroup = "trails[1, ]",
    drawOptions = pmDrawOptions(allowSelfIntersection = FALSE),
    editOptions = pmEditOptions(allowSelfIntersection = FALSE)
  )
```

In the next version of `Leaflet.pm` it looks like there will be a similar option for cut.

The above works well, but for some reason the test does not seem to apply to an existing feature as shown below.

![mapedit_intersect](https://user-images.githubusercontent.com/837910/51805313-86186b80-2231-11e9-9feb-ce601175c8b0.gif)

**Comment by tim-salabim** [comment] 2019-01-27 18:59
Self intersection is only an issue for polygons. Lines are allowed to self intersect AFAIK. Which poses the question why the drawn line is not allowed to intersect?

**Comment by tim-salabim** [comment] 2019-01-27 19:04
Ah because you set it explicitly. Sorry, my bad. So I'd say we should definitely set `allowSelfIntersection` to false for polygons in mapedit. I am not sure about the scope of leaflet.pm but according to the igc standard, self intersection is never allowed for polygons, so @codeofsumit you might want to think about setting it to false for polygons by default as well.

**Comment by codeofsumit** [comment] 2019-02-19 14:13
@tim-salabim I agree. Will be changed in the next major release👍

**Comment by codeofsumit** [comment] 2019-02-19 14:27
Sorry yea, the issue has to remain open due to the original issue when deleting holes

**Comment by Falke-Design** [comment] 2020-09-10 17:56
@codeofsumit drawing like in the GIF from the OP is no longer available (I don't know why) but should we then close this issue?

**Comment by codeofsumit** [comment] 2020-10-03 19:40
Can't reproduce this anymore. Guess it's fixed? Please reopen if anyone still has this issue.

**Closed by codeofsumit** 2020-10-03 19:40 UTC
Labels: bug, wontfix
