### ISSUE TITLE
Alternate way to provide translations

### ISSUE THREAD

**Issue by IanMayo** [geoman-io/leaflet-geoman#1242] opened 2022-10-18 11:14 UTC
When the user starts to add a new feature using GeoMan, a floating tooltip gives guidance on what to do next, such as `Click to place first vertex`.  In my GeoMan-based application I have an opportunity to improve user-experience - by naming what the vertex relates to.  So, this customisation would display `Click to place first vertex of planned route`. 

From investigating GeoMan I see it's possible to provide a translation file.  But, each change is applied to "global options". It would be great if the new-item tooltip could be specified in the `enableDraw()` options object.  The `tooltip` toggle is in there, so this would be a param to override the tooltip content.

**Comment by Falke-Design** [comment] 2022-11-28 17:00
Duplicate of #1127

**Closed by Falke-Design** 2022-11-28 17:00 UTC

**Comment by IanMayo** [comment] 2022-11-28 17:03
Note for anyone wanting to dynamically change GeoMan translations in the future, this is how we resolved this issue:
![image](https://user-images.githubusercontent.com/1108513/204337929-19c27e31-41aa-4b0c-b8bb-abb638d91482.png)

**Comment by Falke-Design** [comment] 2022-11-28 17:05
Interessting, thank you!
