### ISSUE TITLE
When I use the line tool to draw a box, I can only get 3 sides to draw. Clicking on the first point to close the box deletes the last line.

### ISSUE THREAD

**Issue by kuberlog** [geoman-io/leaflet-geoman#541] opened 2020-02-11 14:42 UTC

**Comment by codeofsumit** [comment] 2020-02-11 14:43
Please show a GIF or explain in clear steps what I need to do in the demo to reproduce the issue (and what the issue is)

**Comment by kuberlog** [comment] 2020-02-11 14:46
<img width="1440" alt="Screen Shot 1398-11-22 at 8 44 46 AM" src="https://user-images.githubusercontent.com/1966377/74246955-ec402700-4caa-11ea-88e3-9ea5c2281e16.png">
<img width="1440" alt="Screen Shot 1398-11-22 at 8 44 50 AM" src="https://user-images.githubusercontent.com/1966377/74246960-ed715400-4caa-11ea-96cf-a83491d455de.png">

**Comment by codeofsumit** [comment] 2020-02-11 14:49
Thanks Colin, that's the expected behaviour right now. Clicking on any existing marker will finish drawing.
From your post I assume you expect that clicking on an existing marker will draw the last line as well before finishing?

This would be a breaking change to existing functionality. I won't fix this for now but if more people would like to change this behaviour, upvote this issue.

If you expect a different functionality entirely, let's continue the conversation in here.

**Closed by codeofsumit** 2020-02-11 14:49 UTC
Labels: repro needed

**Comment by kuberlog** [comment] 2020-02-11 15:43
I know it is the "expected behavior", but it is bad design.

**Comment by pedhenrique** [comment] 2020-02-19 04:41
I also would love to see this change.

**Comment by mike16889** [comment] 2021-08-01 01:38
I would find this useful if this was possible as a toggle. in my main project it would not suit, but in a side project it is exactly what i want, so maybe being able to pass an option when enabling draw.

I think as a way around it I might use the polygon, make the working layer have no fill, then on completion getLatLngs(), remove layer and create a new polyline layer.
