### ISSUE TITLE
 syncLayersOnDrag bug 

### ISSUE THREAD

**Issue by Spokt1** [geoman-io/leaflet-geoman#1119] opened 2022-03-04 11:09 UTC
Good afternoon, please tell me, I ran into such a problem that in version 2.11.4 it became impossible to drag 1 polygon, but only a group. Couldn't you see [my example](https://codesandbox.io/s/sweet-snowflake-yx9l5p) . Thank you in advance

**Comment by Falke-Design** [comment] 2022-03-04 12:38
The problem is `renderer: L.canvas(),`.

Will be fixed, thank you for reporting. As workaround you can use `preferCanvas: true`

**Comment by Spokt1** [comment] 2022-03-04 13:03
Thank you for your answer and for the plugin in general

**Comment by Falke-Design** [comment] 2022-04-24 17:59
Fixed with #1069

**Closed by Falke-Design** 2022-04-24 17:59 UTC
Labels: bug
